env:
  global:
    - CC_TEST_REPORTER_ID=18eb5b794e3c857588c1f3f6c38916534dbb01ddaed077c75f95d3ab88c6c38f


language: python
python:
    - 3.8.2

before_install:
    - pip install poetry

install:
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
